### ISSUE TITLE
Incorrect text color after printing usage

### ISSUE THREAD

**Issue by jodavis** [aspnet/HttpRepl#109] opened 2019-07-23 05:09 UTC
When entering an incorrect command, usage is printed. The usage is printed in a different color, and the color doesn't reset before printing the next prompt.

For example, when omitting the header value after `-h` in the following sample

![image](https://user-images.githubusercontent.com/6740581/61684139-3214ae00-accd-11e9-805a-b21f8fb71192.png)

**Comment by tlmii** [comment] 2019-07-26 22:12
This is interesting. 

`Usage: ` is actually the only thing that is supposed to be colored here (it's bold). It appears that the issue is that, when we set something to be bold (as we're doing here with "Usage: ") we are basically saying `[StartBold]Usage: [StartNormalColorAndIntensity]`. But in this case "Normal" is not the same as your default color scheme in your console. So `[StartBold]` sets it to the same thing as you already had it set to, and `[StartNormalColorAndIntensity]` changes it to something else and that continues on.

We use a different variant of that `[StartNormalColorAndIntensity]` for closing off colors - effectively `[StartDefaultForegroundColor]`. It looks like if we use that to close off Bold as well, this problem goes away.

I've taken a stab at it in #121 - @jodavis can you try grabbing that branch/build and seeing if it works for you with your console configuration?

**Comment by jodavis** [comment] 2019-08-02 19:11
@tlmii It fixes the problem in that there is no color change now.
![image](https://user-images.githubusercontent.com/6740581/62393292-9da51980-b51e-11e9-981e-d0ebbb86ef25.png)

**Closed** 2019-08-02 23:38 UTC
Labels: bug
